const express = require("express");
const router = express.Router();
const { createClothing,getCategories,getMyListings,getClothingById,updateClothing,deleteClothing } = require("../controllers/clothingController");
const { verifyToken } = require("../middleware/authMiddleware");
router.post("/",verifyToken,createClothing);
router.get("/categories",verifyToken,getCategories);
router.get("/my-listings",verifyToken,getMyListings);
router.get("/:id",verifyToken,getClothingById);
router.put("/:id",verifyToken,updateClothing);
router.delete("/:id",verifyToken,deleteClothing);
module.exports = router;