module.exports = {
  NEW_LISTING: "NEW_LISTING",

  NEW_SWAP_REQUEST: "NEW_SWAP_REQUEST",
  SWAP_ACCEPTED: "SWAP_ACCEPTED",
  SWAP_REJECTED: "SWAP_REJECTED",
  SWAP_CANCELLED: "SWAP_CANCELLED",
  SWAP_COMPLETED: "SWAP_COMPLETED",

  DISPUTE_RAISED: "DISPUTE_RAISED",
  DISPUTE_STATUS_UPDATED: "DISPUTE_STATUS_UPDATED",
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED",
  NEW_MESSAGE: "NEW_MESSAGE",

  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

  ADMIN_ANNOUNCEMENT: "ADMIN_ANNOUNCEMENT",
};
